services:
  client:
    container_name: client
    build: ./client/
    environment:
      - PORT=3000
    ports:
      - 8080:3000
    restart: if-failed

  server:
    container_name: server
    build: ./server/
    environment:
      - PORT=8000
    ports:
      - 8001:8000
    restart: if-failed
    networks: 
      - backend

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis
    restart: always
    networks: 
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - ALLOW_ORIGIN=*
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: always
    networks: 
      - backend

networks:
  backend:
    driver: bridge
